# narrowly focused ansible deployment playbook for www.mikeandwan.us
---
- name: Configure Service Account
  hosts: webservers
  become: true

  tasks:
    - name: Add Service Account
      ansible.builtin.user:
        name: "{{ svcacct_name }}"
        password: "{{ svcacct_pwd | password_hash('sha512') }}"
        update_password: always
        state: present

    # fedora creates a unique subuid range automatically, so need to do this via usermod here

    - name: Enable Linger for Service Account
      ansible.builtin.command:
        cmd: loginctl enable-linger "{{ svcacct_name | quote }}"

    - name: Add SSH key to authorized_keys
      ansible.posix.authorized_key:
        user: "{{ svcacct_name }}"
        key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"
        state: present

- name: Configure Application
  hosts: webservers
  remote_user: "{{ svcacct_name }}"

  tasks:
    - name: Pull Container Images
      become: true
      become_user: "{{ svcacct_name }}"
      containers.podman.podman_image:
        name: "{{ item }}"
      loop:
        - "docker.io/aerisg222/maw-www:latest"
        - "docker.io/library/postgres:17.5-bookworm"

    - name: Create Pod Quadlet
      containers.podman.podman_pod:
        name: "{{ pod }}"
        state: quadlet
        ports:
          - "8080:8080"
