# narrowly focused ansible deployment playbook for www.mikeandwan.us
---
- name: Configure Service Account
  hosts: webservers
  become: true

  tasks:
    - name: Add Service Account
      ansible.builtin.user:
        name: "{{ svcacct_name }}"
        password: "{{ svcacct_pwd | password_hash('sha512') }}"
        update_password: always
        state: present

    # fedora creates a unique subuid range automatically, so need to do this via usermod here

    - name: Enable Linger for Service Account
      ansible.builtin.command:
        cmd: loginctl enable-linger "{{ svcacct_name | quote }}"

    - name: Add SSH key to authorized_keys
      ansible.posix.authorized_key:
        user: "{{ svcacct_name }}"
        key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"
        state: present

- name: Configure Application
  hosts: webservers
  remote_user: "{{ svcacct_name }}"
  vars:
    pod: pod-www
    img_maw_www: "docker.io/aerisg222/maw-www:latest"
    img_postgres: "docker.io/library/postgres:17.5-bookworm"
    dir_pgdata: "/home/{{ svcacct_name }}/maw-www/pg-data"
    dir_pgsecrets: "/home/{{ svcacct_name }}/maw-www/pg-secrets"

  tasks:
    - name: Create Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ dir_pgdata }}"
        - "{{ dir_pgsecrets }}"

    - name: Generate PG Password File
      ansible.builtin.template:
        src: pgpwd.j2
        dest: "{{ dir_pgsecrets }}/psql-postgres"
        mode: u+rw

    - name: Pull Container Images
      containers.podman.podman_image:
        name: "{{ item }}"
      loop:
        - "{{ img_maw_www }}"
        - "{{ img_postgres }}"

    - name: Create Pod Quadlet
      containers.podman.podman_pod:
        name: "{{ pod }}"
        state: quadlet
        ports:
          - "8080:8080"

    - name: Create Postgres Quadlet
      containers.podman.podman_container:
        name: maw-www-postgres
        image: "{{ img_postgres }}"
        state: quadlet
        read_only: true
        pod: "{{ pod }}"
        env:
          POSTGRES_PASSWORD_FILE: "/secrets/psql-postgres"
        volumes:
          - "{{ dir_pgdata }}:/var/lib/postgresql/data:Z"
          - "{{ dir_pgsecrets }}:/secrets:ro,Z"
        quadlet_options:
          - "AutoUpdate=registry"
          - "Pull=newer"
          - "ReadOnly=true"
          - |
            [Install]
            WantedBy=default.target
